# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:

    docker:
      - image: circleci/python:3.7.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install --upgrade pip
            pip3 install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: write config
          command: |
            echo '{' > config.json
            echo '"token": "'$token'"' >> config.json
            echo '}' >> config.json

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            timeout --preserve-status -s SIGINT --kill-after=30 60 python3 main.py

      - store_artifacts:
          path: test-reports
          destination: test-reports
